# Generated by Django 5.2.17 on 2026-08-27 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tom_targets', '0030_alter_basetarget_slope'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateTarget',
            fields=[
                ('basetarget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tom_targets.basetarget')),
                ('classification', models.CharField(default='Microlensing PSPL', max_length=50)),
                ('category', models.CharField(default='Microlensing stellar/planet', max_length=50)),
                ('t0', models.FloatField(default=0)),
                ('t0_error', models.FloatField(default=0)),
                ('u0', models.FloatField(default=0)),
                ('u0_error', models.FloatField(default=0)),
                ('tE', models.FloatField(default=0)),
                ('tE_error', models.FloatField(default=0)),
                ('piEN', models.FloatField(default=0)),
                ('piEN_error', models.FloatField(default=0)),
                ('piEE', models.FloatField(default=0)),
                ('piEE_error', models.FloatField(default=0)),
                ('rho', models.FloatField(default=0)),
                ('rho_error', models.FloatField(default=0)),
                ('s', models.FloatField(default=0)),
                ('s_error', models.FloatField(default=0)),
                ('q', models.FloatField(default=0)),
                ('q_error', models.FloatField(default=0)),
                ('alpha', models.FloatField(default=0)),
                ('alpha_error', models.FloatField(default=0)),
                ('source_magnitude', models.FloatField(default=0)),
                ('source_mag_error', models.FloatField(default=0)),
                ('blend_magnitude', models.FloatField(default=0)),
                ('blend_mag_error', models.FloatField(default=0)),
                ('baseline_magnitude', models.FloatField(default=0)),
                ('baseline_mag_error', models.FloatField(default=0)),
                ('last_fit', models.FloatField(default=2446756.5)),
                ('chi2', models.FloatField(default=99999.9999)),
                ('red_chi2', models.FloatField(default=99999.9999)),
                ('ks_test', models.FloatField(default=0)),
                ('sw_test', models.FloatField(default=0)),
                ('ad_test', models.FloatField(default=0)),
                ('mag_now', models.FloatField(default=0)),
                ('mag_now_passband', models.CharField(blank=True, default='', max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'target',
                'permissions': (('view_target', 'View Target'), ('add_target', 'Add Target'), ('change_target', 'Change Target'), ('delete_target', 'Delete Target')),
            },
            bases=('tom_targets.basetarget',),
        ),
    ]
