# Generated by Django 5.2.17 on 2026-08-27 21:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0001_initial'),
        ('tom_targets', '0030_alter_basetarget_slope'),
    ]

    operations = [
        migrations.CreateModel(
            name='RGESAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roman_id', models.CharField(max_length=100, verbose_name='Roman ID')),
                ('ra', models.FloatField(blank=True, help_text='Right Ascension, in degrees.', null=True, verbose_name='Right Ascension')),
                ('dec', models.FloatField(blank=True, help_text='Declination, in degrees.', null=True, verbose_name='Declination')),
                ('alert_neural_network_confidence', models.DecimalField(decimal_places=1, help_text='Classification confidence as a percentage', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('alert_delta_chi2', models.DecimalField(decimal_places=3, help_text='Classification confidence in a delta chi2', max_digits=10, null=True)),
                ('alert_classification', models.CharField(choices=[('Microlensing', 'Microlensing'), ('Flare', 'Flare'), ('Variable star', 'Variable star'), ('Solar System object', 'Solar System object'), ('Other', 'Other'), ('Unknown', 'Unknown')], default='Unknown', max_length=30, null=True)),
                ('ffp_candidate', models.BooleanField(default=False)),
                ('alert_origin', models.CharField(blank=True, max_length=60, null=True, verbose_name='Alert Origin')),
                ('alert_notes', models.TextField(blank=True, null=True)),
                ('alert_t0', models.DecimalField(decimal_places=5, help_text='Time of microlensing event peak as a Julian Date', max_digits=13, null=True, validators=[django.core.validators.MinValueValidator(2433282.5), django.core.validators.MaxValueValidator(2470000.0)])),
                ('alert_tE', models.DecimalField(decimal_places=5, help_text='Einstein crossing time of a microlensing event in days', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1000.0)])),
                ('alert_u0', models.DecimalField(decimal_places=6, help_text='Impact parameter of a microlensing event', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('alert_rho', models.DecimalField(decimal_places=4, help_text='Angular source size normalized by the angular Einstein radius of a microlensing event', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(99.0)])),
                ('alert_peak_mag', models.DecimalField(decimal_places=3, help_text='Peak brightness in magnitudes', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(-10.0), django.core.validators.MaxValueValidator(30.0)])),
                ('alert_baseline_mag', models.DecimalField(decimal_places=3, help_text='Baseline brightness in magnitudes', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(-10.0), django.core.validators.MaxValueValidator(30.0)])),
                ('alert_mag_passband', models.CharField(default='unknown', max_length=15, null=True)),
                ('alert_timestamp', models.DateTimeField(blank=True, null=True)),
                ('lightcurve_file', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'rges_alert',
                'permissions': (('view_alert', 'View Alert'), ('add_alert', 'Add Alert'), ('change_alert', 'Change Alert'), ('delete_alert', 'Delete Alert')),
            },
        ),
        migrations.RenameModel(
            old_name='CandidateTarget',
            new_name='RogueTarget',
        ),
    ]
