# Generated by Django 5.2.17 on 2026-08-27 21:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0002_rgesalert_rename_candidatetarget_roguetarget'),
    ]

    operations = [
        migrations.AddField(
            model_name='rgesalert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rgesalert',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
