# Generated by Django 5.2.17 on 2026-08-28 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0003_rgesalert_created_at_rgesalert_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='rgesalert',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='custom_code.roguetarget'),
        ),
    ]
