# Generated by Django 5.2.17 on 2026-08-28 21:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0004_rgesalert_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rgesalert',
            name='alert_baseline_mag',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Baseline brightness in magnitudes', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(-10.0), django.core.validators.MaxValueValidator(30.0)]),
        ),
        migrations.AlterField(
            model_name='rgesalert',
            name='alert_delta_chi2',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Classification confidence in a delta chi2', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rgesalert',
            name='alert_neural_network_confidence',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Classification confidence as a percentage', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='rgesalert',
            name='alert_peak_mag',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Peak brightness in magnitudes', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(-10.0), django.core.validators.MaxValueValidator(30.0)]),
        ),
        migrations.AlterField(
            model_name='rgesalert',
            name='alert_rho',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Angular source size normalized by the angular Einstein radius of a microlensing event', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(99.0)]),
        ),
        migrations.AlterField(
            model_name='rgesalert',
            name='alert_t0',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='Time of microlensing event peak as a Julian Date', max_digits=13, null=True, validators=[django.core.validators.MinValueValidator(2433282.5), django.core.validators.MaxValueValidator(2470000.0)]),
        ),
        migrations.AlterField(
            model_name='rgesalert',
            name='alert_tE',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='Einstein crossing time of a microlensing event in days', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1000.0)]),
        ),
        migrations.AlterField(
            model_name='rgesalert',
            name='alert_u0',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Impact parameter of a microlensing event', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
