# Generated by Django 5.2.17 on 2026-08-28 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0005_alter_rgesalert_alert_baseline_mag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(blank=True, default='Unknown', max_length=15, null=True)),
                ('t0', models.FloatField(blank=True, default=0, null=True)),
                ('t0_error', models.FloatField(blank=True, default=0, null=True)),
                ('u0', models.FloatField(blank=True, default=0, null=True)),
                ('u0_error', models.FloatField(blank=True, default=0, null=True)),
                ('tE', models.FloatField(blank=True, default=0, null=True)),
                ('tE_error', models.FloatField(blank=True, default=0, null=True)),
                ('piEN', models.FloatField(blank=True, default=0, null=True)),
                ('piEN_error', models.FloatField(blank=True, default=0, null=True)),
                ('piEE', models.FloatField(blank=True, default=0, null=True)),
                ('piEE_error', models.FloatField(blank=True, default=0, null=True)),
                ('rho', models.FloatField(blank=True, default=0, null=True)),
                ('rho_error', models.FloatField(blank=True, default=0, null=True)),
                ('peak_amplitude', models.FloatField(blank=True, default=0, null=True)),
                ('rise_time', models.FloatField(blank=True, default=0, null=True)),
                ('tau1', models.FloatField(blank=True, default=0, null=True)),
                ('tau2', models.FloatField(blank=True, default=0, null=True)),
                ('equivalent_duration', models.FloatField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_models', to='custom_code.roguetarget')),
            ],
            options={
                'verbose_name': 'target_model',
                'permissions': (('view_model', 'View Model'), ('add_model', 'Add Model'), ('change_model', 'Change Model'), ('delete_model', 'Delete Model')),
            },
        ),
    ]
