# Generated by Django 5.2.17 on 2026-08-28 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0006_targetmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetmodel',
            name='model_type',
            field=models.CharField(blank=True, choices=[('Microlensing', 'Microlensing'), ('Flare', 'Flare'), ('Unknown', 'Unknown')], default='Unknown', max_length=15, null=True),
        ),
    ]
