# Generated by Django 5.2.17 on 2026-08-31 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0007_alter_targetmodel_model_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetmodel',
            name='equivalent_duration',
            field=models.FloatField(blank=True, db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='targetmodel',
            name='model_type',
            field=models.CharField(blank=True, choices=[('Microlensing', 'Microlensing'), ('Flare', 'Flare'), ('Unknown', 'Unknown')], db_index=True, default='Unknown', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='targetmodel',
            name='peak_amplitude',
            field=models.FloatField(blank=True, db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='targetmodel',
            name='piEE',
            field=models.FloatField(blank=True, db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='targetmodel',
            name='piEN',
            field=models.FloatField(blank=True, db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='targetmodel',
            name='rho',
            field=models.FloatField(blank=True, db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='targetmodel',
            name='rise_time',
            field=models.FloatField(blank=True, db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='targetmodel',
            name='t0',
            field=models.FloatField(blank=True, db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='targetmodel',
            name='tE',
            field=models.FloatField(blank=True, db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='targetmodel',
            name='tau1',
            field=models.FloatField(blank=True, db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='targetmodel',
            name='tau2',
            field=models.FloatField(blank=True, db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='targetmodel',
            name='u0',
            field=models.FloatField(blank=True, db_index=True, default=0, null=True),
        ),
    ]
