# Generated by Django 5.2.17 on 2026-09-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0008_alter_targetmodel_equivalent_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetmodel',
            name='chisq',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
