# Generated by Django 5.2.17 on 2026-09-01 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0009_targetmodel_chisq'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetmodel',
            name='model_category',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
