# Generated by Django 5.2.17 on 2026-09-02 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0010_targetmodel_model_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='rgesalert',
            name='alert_contents',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rgesalert',
            name='alert_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
