# Generated by Django 5.2.17 on 2026-09-03 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0011_rgesalert_alert_contents_rgesalert_alert_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(blank=True, choices=[('Microlensing', 'Microlensing'), ('Flare', 'Flare'), ('Unknown', 'Unknown')], db_index=True, default='Unknown', max_length=15, null=True)),
                ('chisq', models.FloatField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_models', to='custom_code.roguetarget')),
            ],
        ),
        migrations.CreateModel(
            name='FlareModel',
            fields=[
                ('eventmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='custom_code.eventmodel')),
                ('peak_amplitude', models.FloatField(blank=True, db_index=True, default=0, null=True)),
                ('rise_time', models.FloatField(blank=True, db_index=True, default=0, null=True)),
                ('tau1', models.FloatField(blank=True, db_index=True, default=0, null=True)),
                ('tau2', models.FloatField(blank=True, db_index=True, default=0, null=True)),
                ('equivalent_duration', models.FloatField(blank=True, db_index=True, default=0, null=True)),
            ],
            bases=('custom_code.eventmodel',),
        ),
        migrations.CreateModel(
            name='MicrolensingModel',
            fields=[
                ('eventmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='custom_code.eventmodel')),
                ('model_category', models.CharField(blank=True, max_length=30, null=True)),
                ('t0', models.FloatField(blank=True, db_index=True, default=0, null=True)),
                ('t0_error', models.FloatField(blank=True, default=0, null=True)),
                ('u0', models.FloatField(blank=True, db_index=True, default=0, null=True)),
                ('u0_error', models.FloatField(blank=True, default=0, null=True)),
                ('tE', models.FloatField(blank=True, db_index=True, default=0, null=True)),
                ('tE_error', models.FloatField(blank=True, default=0, null=True)),
                ('piEN', models.FloatField(blank=True, db_index=True, default=0, null=True)),
                ('piEN_error', models.FloatField(blank=True, default=0, null=True)),
                ('piEE', models.FloatField(blank=True, db_index=True, default=0, null=True)),
                ('piEE_error', models.FloatField(blank=True, default=0, null=True)),
                ('rho', models.FloatField(blank=True, db_index=True, default=0, null=True)),
                ('rho_error', models.FloatField(blank=True, default=0, null=True)),
            ],
            bases=('custom_code.eventmodel',),
        ),
        migrations.DeleteModel(
            name='TargetModel',
        ),
    ]
