# Generated by Django 5.2.17 on 2026-09-03 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0012_eventmodel_flaremodel_microlensingmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmodel',
            name='target',
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_start', models.FloatField(blank=True, null=True)),
                ('window_end', models.FloatField(blank=True, null=True)),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='custom_code.roguetarget')),
            ],
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_models', to='custom_code.event'),
        ),
    ]
