# Generated by Django 5.2.17 on 2026-09-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0013_remove_eventmodel_target_event_eventmodel_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
