# Generated by Django 5.2.17 on 2026-09-03 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0014_event_event_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rgesalert',
            name='target',
        ),
        migrations.AddField(
            model_name='rgesalert',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='custom_code.event'),
        ),
    ]
