# Generated by Django 5.2.17 on 2026-09-09 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0015_remove_rgesalert_target_rgesalert_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='bic',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='fit_covariance',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='rgesalert',
            name='alert_origin',
            field=models.CharField(blank=True, choices=[('aethra', 'Aethra'), ('neural network', 'Neural Network'), ('unknown', 'Unknown')], default='unknown', max_length=60, null=True, verbose_name='Alert Origin'),
        ),
    ]
