# Generated by Django 5.2.17 on 2026-09-10 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0016_eventmodel_bic_eventmodel_fit_covariance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DavenportFlareModel',
            fields=[
                ('eventmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='custom_code.eventmodel')),
                ('t_peak', models.FloatField(blank=True, db_index=True, default=0, null=True)),
                ('t_peak_error', models.FloatField(blank=True, default=0, null=True)),
                ('peak_amplitude', models.FloatField(blank=True, db_index=True, default=0, null=True)),
                ('peak_amplitude_error', models.FloatField(blank=True, default=0, null=True)),
                ('t_FWHM', models.FloatField(blank=True, db_index=True, default=0, null=True)),
                ('t_FWHM_error', models.FloatField(blank=True, default=0, null=True)),
            ],
            bases=('custom_code.eventmodel',),
        ),
        migrations.CreateModel(
            name='FSPLModel',
            fields=[
                ('eventmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='custom_code.eventmodel')),
                ('t0', models.FloatField(blank=True, db_index=True, default=0, null=True)),
                ('t0_error', models.FloatField(blank=True, default=0, null=True)),
                ('u0', models.FloatField(blank=True, db_index=True, default=0, null=True)),
                ('u0_error', models.FloatField(blank=True, default=0, null=True)),
                ('tE', models.FloatField(blank=True, db_index=True, default=0, null=True)),
                ('tE_error', models.FloatField(blank=True, default=0, null=True)),
                ('piEN', models.FloatField(blank=True, db_index=True, default=0, null=True)),
                ('piEN_error', models.FloatField(blank=True, default=0, null=True)),
                ('piEE', models.FloatField(blank=True, db_index=True, default=0, null=True)),
                ('piEE_error', models.FloatField(blank=True, default=0, null=True)),
                ('rho', models.FloatField(blank=True, db_index=True, default=0, null=True)),
                ('rho_error', models.FloatField(blank=True, default=0, null=True)),
                ('blend_parameters', models.JSONField(blank=True, default=dict, null=True)),
            ],
            bases=('custom_code.eventmodel',),
        ),
        migrations.CreateModel(
            name='PitkinFlareModel',
            fields=[
                ('eventmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='custom_code.eventmodel')),
                ('t_peak', models.FloatField(blank=True, db_index=True, default=0, null=True)),
                ('t_peak_error', models.FloatField(blank=True, default=0, null=True)),
                ('peak_amplitude', models.FloatField(blank=True, db_index=True, default=0, null=True)),
                ('peak_amplitude_error', models.FloatField(blank=True, default=0, null=True)),
                ('tau_gaussian_rise', models.FloatField(blank=True, db_index=True, default=0, null=True)),
                ('tau_gaussian_rise_error', models.FloatField(blank=True, default=0, null=True)),
                ('tau_exponential_decay', models.FloatField(blank=True, db_index=True, default=0, null=True)),
                ('tau_exponential_decay_error', models.FloatField(blank=True, default=0, null=True)),
            ],
            bases=('custom_code.eventmodel',),
        ),
        migrations.CreateModel(
            name='PSPLModel',
            fields=[
                ('eventmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='custom_code.eventmodel')),
                ('t0', models.FloatField(blank=True, db_index=True, default=0, null=True)),
                ('t0_error', models.FloatField(blank=True, default=0, null=True)),
                ('u0', models.FloatField(blank=True, db_index=True, default=0, null=True)),
                ('u0_error', models.FloatField(blank=True, default=0, null=True)),
                ('tE', models.FloatField(blank=True, db_index=True, default=0, null=True)),
                ('tE_error', models.FloatField(blank=True, default=0, null=True)),
                ('piEN', models.FloatField(blank=True, db_index=True, default=0, null=True)),
                ('piEN_error', models.FloatField(blank=True, default=0, null=True)),
                ('piEE', models.FloatField(blank=True, db_index=True, default=0, null=True)),
                ('piEE_error', models.FloatField(blank=True, default=0, null=True)),
                ('blend_parameters', models.JSONField(blank=True, default=dict, null=True)),
            ],
            bases=('custom_code.eventmodel',),
        ),
        migrations.CreateModel(
            name='SkewNormalModel',
            fields=[
                ('eventmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='custom_code.eventmodel')),
                ('t_peak', models.FloatField(blank=True, db_index=True, default=0, null=True)),
                ('t_peak_error', models.FloatField(blank=True, default=0, null=True)),
                ('peak_amplitude', models.FloatField(blank=True, db_index=True, default=0, null=True)),
                ('peak_amplitude_error', models.FloatField(blank=True, default=0, null=True)),
                ('omega', models.FloatField(blank=True, db_index=True, default=0, null=True)),
                ('omega_error', models.FloatField(blank=True, default=0, null=True)),
                ('alpha', models.FloatField(blank=True, db_index=True, default=0, null=True)),
                ('alpha_error', models.FloatField(blank=True, default=0, null=True)),
            ],
            bases=('custom_code.eventmodel',),
        ),
        migrations.CreateModel(
            name='StraightLineModel',
            fields=[
                ('eventmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='custom_code.eventmodel')),
                ('intercept', models.FloatField(blank=True, default=0, null=True)),
                ('intercept_error', models.FloatField(blank=True, default=0, null=True)),
                ('gradient', models.FloatField(blank=True, default=0, null=True)),
                ('gradient_error', models.FloatField(blank=True, default=0, null=True)),
            ],
            bases=('custom_code.eventmodel',),
        ),
        migrations.RemoveField(
            model_name='microlensingmodel',
            name='eventmodel_ptr',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='window_end',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='window_start',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='event',
            name='BIC_FSPL',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='BIC_FSPL_bestflare',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='DIA_centroid_shift',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='Nlinked_events',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='Npoint_above_3sigma',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='PSF_centroid_shift',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='angular_separation_moving_object',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='coverage_fraction',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='delta_chi2_FSPL',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='delta_chi2_FSPL_bestflare',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='frac_below_baseline',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='max_excursion_below_baseline',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='max_peak_periodogram',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='nearest_moving_object',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='period',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='second_peak_mag',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='symmetry',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='time_to_second_peak',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roguetarget',
            name='angular_separation_flare_star',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='roguetarget',
            name='angular_separation_variable',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='roguetarget',
            name='nearest_flare_star',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='roguetarget',
            name='nearest_variable_star',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='model_type',
            field=models.CharField(blank=True, choices=[('PSPL microlensing', 'PSPL microlensing'), ('FSPL microlensing', 'FSPL microlensing'), ('Davenport flare', 'Davenport flare'), ('Pitkin flare', 'Pitkin flare'), ('Unknown', 'Unknown')], db_index=True, default='Unknown', max_length=60, null=True),
        ),
        migrations.DeleteModel(
            name='FlareModel',
        ),
        migrations.DeleteModel(
            name='MicrolensingModel',
        ),
    ]
