# Generated by Django 5.2.17 on 2026-09-10 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0017_davenportflaremodel_fsplmodel_pitkinflaremodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WideBoundPlanetModel',
            fields=[
                ('eventmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='custom_code.eventmodel')),
                ('tc', models.FloatField(blank=True, db_index=True, default=0, null=True)),
                ('tc_error', models.FloatField(blank=True, default=0, null=True)),
                ('uc', models.FloatField(blank=True, db_index=True, default=0, null=True)),
                ('uc_error', models.FloatField(blank=True, default=0, null=True)),
                ('tE', models.FloatField(blank=True, db_index=True, default=0, null=True)),
                ('tE_error', models.FloatField(blank=True, default=0, null=True)),
                ('rho', models.FloatField(blank=True, db_index=True, default=0, null=True)),
                ('rho_error', models.FloatField(blank=True, default=0, null=True)),
                ('s', models.FloatField(blank=True, db_index=True, default=0, null=True)),
                ('s_error', models.FloatField(blank=True, default=0, null=True)),
                ('q', models.FloatField(blank=True, db_index=True, default=0, null=True)),
                ('q_error', models.FloatField(blank=True, default=0, null=True)),
                ('alpha', models.FloatField(blank=True, db_index=True, default=0, null=True)),
                ('alpha_error', models.FloatField(blank=True, default=0, null=True)),
                ('blend_parameters', models.JSONField(blank=True, default=dict, null=True)),
            ],
            bases=('custom_code.eventmodel',),
        ),
    ]
