# Generated by Django 5.2.17 on 2026-09-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0018_wideboundplanetmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventmodel',
            old_name='bic',
            new_name='BIC',
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='model_type',
            field=models.CharField(blank=True, choices=[('PSPL microlensing', 'PSPL microlensing'), ('FSPL microlensing', 'FSPL microlensing'), ('Wide bound planet', 'Wide bound planet'), ('Davenport flare', 'Davenport flare'), ('Pitkin flare', 'Pitkin flare'), ('Unknown', 'Unknown')], db_index=True, default='Unknown', max_length=60, null=True),
        ),
    ]
