# Generated by Django 5.2.17 on 2026-09-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0019_rename_bic_eventmodel_bic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fsplmodel',
            name='A',
            field=models.FloatField(blank=True, db_index=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='fsplmodel',
            name='A_error',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='psplmodel',
            name='A',
            field=models.FloatField(blank=True, db_index=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='psplmodel',
            name='A_error',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='wideboundplanetmodel',
            name='A',
            field=models.FloatField(blank=True, db_index=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='wideboundplanetmodel',
            name='A_error',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
