# Generated by Django 5.2.17 on 2026-09-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0020_fsplmodel_a_fsplmodel_a_error_psplmodel_a_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='BIC_FSPL',
            new_name='delta_BIC_FSPL',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='BIC_FSPL_bestflare',
            new_name='delta_BIC_FSPL_bestflare',
        ),
        migrations.AddField(
            model_name='event',
            name='delta_BIC_PSPL',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='delta_BIC_PSPL_bestflare',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='delta_chi2_PSPL',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='delta_chi2_PSPL_bestflare',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
