# Generated by Django 5.2.17 on 2026-09-14 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0023_alter_eventmodel_model_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='roguetarget',
            name='frac_below_baseline',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roguetarget',
            name='max_excursion_below_baseline',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
