# Generated by Django 5.2.17 on 2026-09-14 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0024_roguetarget_frac_below_baseline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='frac_below_baseline',
        ),
        migrations.RemoveField(
            model_name='event',
            name='max_excursion_below_baseline',
        ),
    ]
