# Generated by Django 5.2.17 on 2026-09-15 18:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0024_roguetarget_frac_below_baseline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlareStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(360.0)])),
                ('dec', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
