# Generated by Django 5.2.17 on 2026-09-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0025_flarestar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlareStar',
        ),
        migrations.AddField(
            model_name='variablestar',
            name='moa_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
