# Generated by Django 5.2.17 on 2026-09-15 19:07

from django.db import migrations


class Migration(migrations.Migration):
    """
    frac_below_baseline and max_excursion_below_baseline were dropped from the
    custom_code_event table by hand when they were moved to RogueTarget (see
    0024_roguetarget_frac_below_baseline_and_more), without a corresponding
    RemoveField migration -- so Django's migration state still expected these
    columns on Event while the live database no longer had them, causing
    "column custom_code_event.frac_below_baseline does not exist" on any query
    that touched Event. SeparateDatabaseAndState updates Django's tracked state
    to match the database that already exists, without attempting to DROP
    COLUMNs that are already gone (which would itself error).
    """

    dependencies = [
        ('custom_code', '0026_delete_flarestar_variablestar_moa_id'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='event',
                    name='frac_below_baseline',
                ),
                migrations.RemoveField(
                    model_name='event',
                    name='max_excursion_below_baseline',
                ),
            ],
            database_operations=[],
        ),
    ]
