# Generated by Django 5.2.17 on 2026-09-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0027_remove_event_frac_below_baseline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roguetarget',
            name='nearest_variable_type',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
