# Generated by Django 5.2.17 on 2026-09-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0028_roguetarget_nearest_variable_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='event_thumbnails/%Y/%m/%d/'),
        ),
    ]
