# Generated by Django 5.2.17 on 2026-09-17 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0029_event_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rgesalert',
            name='alert_origin',
            field=models.CharField(blank=True, choices=[('aethra', 'Aethra'), ('neural network', 'Neural Network'), ('MSOS', 'MSOS'), ('unknown', 'Unknown')], default='unknown', max_length=60, null=True, verbose_name='Alert Origin'),
        ),
    ]
