# Generated by Django 5.2.17 on 2026-09-21 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0030_alter_rgesalert_alert_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='red_chisq',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
