# Generated by Django 5.2.17 on 2026-09-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0031_eventmodel_red_chisq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roguetarget',
            name='frac_below_baseline',
        ),
        migrations.RemoveField(
            model_name='roguetarget',
            name='max_excursion_below_baseline',
        ),
        migrations.AddField(
            model_name='event',
            name='frac_below_baseline',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='max_excursion_below_baseline',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
