# Generated by Django 5.2.17 on 2026-09-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0033_alter_eventmodel_model_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='corner_plot',
            field=models.ImageField(blank=True, null=True, upload_to='eventmodel_plots/%Y/%m/%d/'),
        ),
    ]
