# Generated by Django 5.2.17 on 2026-09-28 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0034_eventmodel_corner_plot'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='fit_method',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
