# Generated by Django 5.2.17 on 2026-09-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0035_eventmodel_fit_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='tau',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='tau_threshold',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
