# Generated by Django 5.2.17 on 2026-09-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Moves max_peak_periodogram/period from Event to RogueTarget.

    This originally depended on 0037_merge_20260930_1649, an auto-generated
    merge migration needed only because a stale, orphaned duplicate migration
    -- 0025_remove_event_frac_below_baseline_and_more.py -- was left on disk
    as a second, disconnected leaf of the migration graph (a real duplicate of
    0027_remove_event_frac_below_baseline_and_more.py, which is the migration
    actually chained into history via 0026; both did the same RemoveField,
    apparently from two branches merged without reconciling the migration
    numbering). That duplication also corrupted makemigrations' autodetected
    state for this migration: it believed Event no longer had
    frac_below_baseline/max_excursion_below_baseline (removed once by the
    orphan 0025, once more -- redundantly -- by 0027) and so proposed
    re-adding them here, colliding with the real columns already added by
    0032_remove_roguetarget_frac_below_baseline_and_more ("column
    frac_below_baseline of relation custom_code_event already exists").
    Both the orphan 0025 and the now-unneeded 0037 merge have been deleted,
    and this migration repointed at 0036 directly, with the bogus
    frac_below_baseline/max_excursion_below_baseline AddFields removed --
    those fields are untouched by this change and already exist on Event.
    """

    dependencies = [
        ('custom_code', '0036_eventmodel_tau_eventmodel_tau_threshold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='max_peak_periodogram',
        ),
        migrations.RemoveField(
            model_name='event',
            name='period',
        ),
        migrations.AddField(
            model_name='roguetarget',
            name='max_peak_periodogram',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roguetarget',
            name='period',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
