# Generated by Django 5.2.17 on 2026-10-01 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0038_remove_event_max_peak_periodogram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='peak_mag',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
