# Generated by Django 5.2.17 on 2026-10-07 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0039_event_peak_mag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rgesalert',
            name='alert_origin',
            field=models.CharField(blank=True, choices=[('pyaethra', 'pyAethra'), ('neural network', 'Neural Network'), ('MSOS', 'MSOS'), ('unknown', 'Unknown')], default='unknown', max_length=60, null=True, verbose_name='Alert Origin'),
        ),
    ]
