# Generated by Django 5.2.17 on 2026-10-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0040_alter_rgesalert_alert_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
