# Generated by Django 5.2.17 on 2026-10-08 22:03

import django.db.models.deletion
from django.db import migrations, models


def set_target_from_event(apps, schema_editor):
    """Alerts recorded before they had a target of their own take their event's"""
    RGESAlert = apps.get_model('custom_code', 'RGESAlert')
    Event = apps.get_model('custom_code', 'Event')
    for event in Event.objects.exclude(target=None).iterator():
        RGESAlert.objects.filter(event=event, target=None).update(target=event.target)


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0041_alter_event_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rgesalert',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='custom_code.roguetarget'),
        ),
        migrations.RunPython(set_target_from_event, migrations.RunPython.noop),
    ]
