# Generated by Django 5.2.17 on 2026-10-08 22:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0042_rgesalert_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='SourceDiagnostics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(default='Microlensing PSPL', max_length=50)),
                ('category', models.CharField(default='Microlensing stellar/planet', max_length=50)),
                ('source_magnitude', models.FloatField(default=0)),
                ('source_mag_error', models.FloatField(default=0)),
                ('baseline_magnitude', models.FloatField(default=0)),
                ('baseline_mag_error', models.FloatField(default=0)),
                ('nearest_flare_star', models.CharField(blank=True, default='', max_length=60, null=True)),
                ('angular_separation_flare_star', models.FloatField(blank=True, default=0, null=True)),
                ('nearest_variable_star', models.CharField(blank=True, default='', max_length=60, null=True)),
                ('angular_separation_variable', models.FloatField(blank=True, default=0, null=True)),
                ('nearest_variable_type', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('max_peak_periodogram', models.FloatField(blank=True, null=True)),
                ('period', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sourcediagnostics', to='custom_code.roguetarget')),
            ],
            options={
                'verbose_name': 'source diagnostics',
            },
        ),
    ]
