# Generated by Django 5.2.17 on 2026-10-10 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0043_event_created_at_event_updated_at_sourcediagnostics'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcediagnostics',
            name='baseline_mag_passband',
            field=models.CharField(default='', max_length=50),
        ),
    ]
